[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  OPENAI_API_KEY = "OpenAI API Key"
  OPENAI_ASSISTANT_ID = "OpenAI Assistant ID"
